name: qalbuna_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  supabase_flutter: ^2.0.0 
  google_sign_in: ^6.1.4
  intl: ^0.18.1
  http: ^1.1.0 
  audioplayers: ^5.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.1.7
  youtube_player_flutter: ^9.1.2
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_inappwebview: ^6.0.0
  flutter_inappwebview_android: ^1.0.13       
  flutter_inappwebview_platform_interface: ^1.0.10 
  app_links: ^3.4.5
  path_provider_android: ^2.1.0
  shared_preferences_android: ^2.2.0
  url_launcher_android: ^6.1.0
  video_player_android: ^2.4.10
  google_sign_in_android: ^6.1.14 

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
